- name: configure the backend server
  hosts: backend
  become: yes
  tasks:
  - name: disabling default nodeks
    ansible.builtin.command: dnf module disable nodejs -y 

  - name: enabling nodejs20
    ansible.builtin.command: dnf module enable nodejs:20 -y 
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create expense user
    ansible.builtin.user:
      name: expense